[package]
name = "brson-rs"
version = "0.1.0"
authors = ["CKK COBALT"]
description = "JSONとBRSONの相互変換"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brotli = "3.4.0"
bson = "2.8.1"